"""
Explore simulation_events.h5 file structure

This script explores the HDF5 file generated by the june2 C++ simulator.

Expected structure:
  /events/
    - infections: (person_id, infector_id, venue_id, time)
    - deaths: (person_id, venue_id, time)
    - symptom_changes: (person_id, venue_id, time, old_symptom, new_symptom)
    - hospital_admissions: (person_id, hospital_id, time, reason)
    - icu_admissions: (person_id, hospital_id, time)
    - hospital_discharges: (person_id, hospital_id, time, outcome)
  /lookups/
    - people: person details
    - venues: venue details
    - person_activities: person-to-activity mappings
"""

import h5py
import numpy as np

def explore_group(group, indent=0):
    """Recursively explore HDF5 groups and datasets"""
    prefix = "  " * indent
    for key in group.keys():
        item = group[key]
        if isinstance(item, h5py.Group):
            print(f"{prefix}{key}/ (Group)")
            explore_group(item, indent + 1)
        elif isinstance(item, h5py.Dataset):
            print(f"{prefix}{key} (Dataset)")
            print(f"{prefix}  Shape: {item.shape}")
            print(f"{prefix}  Dtype: {item.dtype}")

            if len(item) > 0:
                print(f"{prefix}  First 10 rows:")
                print(f"{prefix}    {item[:10]}")

                # Show column info for structured arrays
                if item.dtype.names:
                    print(f"{prefix}  Column info:")
                    for col_name in item.dtype.names:
                        col_data = item[col_name]
                        # Handle string columns differently
                        if np.issubdtype(col_data.dtype, np.bytes_) or np.issubdtype(col_data.dtype, np.str_):
                            print(f"{prefix}    {col_name}: dtype={col_data.dtype}")
                            unique_vals = np.unique(col_data)
                            if len(unique_vals) <= 20:
                                print(f"{prefix}      Unique values: {unique_vals}")
                            else:
                                print(f"{prefix}      {len(unique_vals)} unique values")
                        else:
                            print(f"{prefix}    {col_name}: dtype={col_data.dtype}, min={col_data.min()}, max={col_data.max()}")
                            if len(np.unique(col_data)) < 20:
                                print(f"{prefix}      Unique values: {np.unique(col_data)}")
            else:
                print(f"{prefix}  (empty)")
            print()

# Open and explore the HDF5 file
with h5py.File('../simulation_events.h5', 'r') as f:
    print("=" * 70)
    print("SIMULATION EVENTS HDF5 FILE STRUCTURE")
    print("=" * 70)
    print(f"\nTop-level groups: {list(f.keys())}\n")

    # Show high-level statistics
    if 'events' in f:
        print("\n--- EVENT COUNTS ---")
        events_group = f['events']
        for event_type in events_group.keys():
            count = len(events_group[event_type])
            print(f"  {event_type}: {count:,}")

    if 'lookups' in f:
        print("\n--- LOOKUP TABLE SIZES ---")
        lookups_group = f['lookups']
        for table_name in lookups_group.keys():
            count = len(lookups_group[table_name])
            print(f"  {table_name}: {count:,}")

    print("\n" + "=" * 70)
    print("DETAILED STRUCTURE")
    print("=" * 70 + "\n")
    explore_group(f)
