"""
Epidemiology Simulation Visualizer

This script creates comprehensive visualizations and statistics from the simulation_events.h5 file
generated by the june2 C++ simulator.

Expected HDF5 structure:
  /events/
    - infections: structured array (person_id, infector_id, venue_id, time)
    - deaths: structured array (person_id, venue_id, time)
    - symptom_changes: structured array (person_id, venue_id, time, old_symptom, new_symptom)
    - hospital_admissions: structured array (person_id, hospital_id, time, reason)
    - icu_admissions: structured array (person_id, hospital_id, time)
    - hospital_discharges: structured array (person_id, hospital_id, time, outcome)
  /lookups/
    - people: person details
    - venues: venue details
    - person_activities: person-activity mappings
"""

import h5py
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter, defaultdict
from datetime import datetime
import pandas as pd

# Set style for better-looking plots
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 8)

class SimulationAnalyzer:
    def __init__(self, h5_path):
        self.h5_path = h5_path
        self.load_data()

    def load_data(self):
        """Load all data from HDF5 file"""
        print("Loading data from HDF5 file...")
        with h5py.File(self.h5_path, 'r') as f:
            # Required events
            self.infections = f['events/infections'][:]
            self.deaths = f['events/deaths'][:]

            # Optional events
            if 'events/symptom_changes' in f:
                self.symptom_changes = f['events/symptom_changes'][:]
            else:
                self.symptom_changes = np.array([], dtype=[('person_id', 'i4'), ('venue_id', 'i4'), ('time', 'f8'), ('old_symptom', 'S64'), ('new_symptom', 'S64')])
                print("  Note: symptom_changes not found")

        print(f"Loaded {len(self.infections)} infections, {len(self.deaths)} deaths, "
              f"{len(self.symptom_changes)} symptom changes")

    def compute_statistics(self):
        """Compute key epidemiological statistics"""
        print("\n" + "="*60)
        print("EPIDEMIOLOGICAL STATISTICS")
        print("="*60)

        # Basic counts
        total_infections = len(self.infections)
        seed_infections = np.sum(self.infections['infector_id'] == -1)
        secondary_infections = total_infections - seed_infections
        total_deaths = len(self.deaths)

        print(f"\nInfection Statistics:")
        print(f"  Total infections: {total_infections:,}")
        print(f"  Seed infections: {seed_infections:,}")
        print(f"  Secondary infections: {secondary_infections:,}")

        # Calculate R0 (basic reproduction number) - infections caused by seed cases
        infectors = self.infections['infector_id']
        seed_ids = self.infections['person_id'][self.infections['infector_id'] == -1]

        infections_by_person = Counter(infectors[infectors != -1])
        seed_offspring = [infections_by_person[seed_id] for seed_id in seed_ids]

        if seed_offspring:
            r0_estimate = np.mean(seed_offspring)
            r0_std = np.std(seed_offspring)
            print(f"\nReproduction Number (R0):")
            print(f"  Mean: {r0_estimate:.2f}")
            print(f"  Std: {r0_std:.2f}")
            print(f"  Min: {min(seed_offspring)}")
            print(f"  Max: {max(seed_offspring)}")
        else:
            print("\nReproduction Number (R0): N/A (no seed infections found)")

        # Symptom distribution
        print(f"\nSymptom Progression:")
        symptom_types = [s.decode('utf-8') if isinstance(s, bytes) else s
                         for s in self.symptom_changes['new_symptom']]
        symptom_counts = Counter(symptom_types)
        for symptom, count in sorted(symptom_counts.items()):
            print(f"  {symptom}: {count:,}")

        # Deaths
        print(f"\nOutcomes:")
        print(f"  Total deaths: {total_deaths:,}")
        if total_infections > 0:
            cfr = (total_deaths / total_infections) * 100
            print(f"  Case Fatality Rate (CFR): {cfr:.2f}%")

        # Timeline
        if len(self.infections) > 0:
            print(f"\nTimeline:")
            print(f"  Simulation duration: {self.infections['time'].max():.1f} days")
            print(f"  First infection: Day {self.infections['time'].min():.1f}")
            print(f"  Last infection: Day {self.infections['time'].max():.1f}")

        if len(self.deaths) > 0:
            print(f"  First death: Day {self.deaths['time'].min():.1f}")
            print(f"  Last death: Day {self.deaths['time'].max():.1f}")

        # Generation times (time between infection and causing new infections)
        gen_times = []
        for infection in self.infections:
            if infection['infector_id'] != -1:
                infector_time = self.infections[
                    self.infections['person_id'] == infection['infector_id']
                ]['time']
                if len(infector_time) > 0:
                    gen_time = infection['time'] - infector_time[0]
                    if gen_time > 0:
                        gen_times.append(gen_time)

        if gen_times:
            print(f"\nGeneration Time:")
            print(f"  Mean: {np.mean(gen_times):.2f} days")
            print(f"  Median: {np.median(gen_times):.2f} days")
            print(f"  Std: {np.std(gen_times):.2f} days")

        return {
            'total_infections': total_infections,
            'seed_infections': seed_infections,
            'secondary_infections': secondary_infections,
            'total_deaths': total_deaths,
            'r0_estimate': r0_estimate if seed_offspring else None,
            'generation_times': gen_times
        }

    def plot_epidemic_curve(self, ax):
        """Plot infections over time"""
        times = self.infections['time']
        bins = np.arange(0, times.max() + 1, 1)
        counts, edges = np.histogram(times, bins=bins)

        ax.bar(edges[:-1], counts, width=0.8, alpha=0.7, color='#e74c3c')
        ax.set_xlabel('Time (days)', fontsize=12)
        ax.set_ylabel('Number of Infections', fontsize=12)
        ax.set_title('Epidemic Curve (Infections Over Time)', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)

        # Add peak annotation
        peak_day = edges[np.argmax(counts)]
        peak_count = counts.max()
        ax.annotate(f'Peak: {peak_count} infections\non day {peak_day:.0f}',
                   xy=(peak_day, peak_count),
                   xytext=(peak_day + 2, peak_count * 0.9),
                   arrowprops=dict(arrowstyle='->', color='black'),
                   fontsize=10)

    def plot_symptom_progression(self, ax):
        """Plot symptom state transitions"""
        # Create transition counts
        transitions = defaultdict(int)
        for event in self.symptom_changes:
            old_sym = event['old_symptom'].decode('utf-8') if isinstance(event['old_symptom'], bytes) else event['old_symptom']
            new_sym = event['new_symptom'].decode('utf-8') if isinstance(event['new_symptom'], bytes) else event['new_symptom']
            transitions[(old_sym, new_sym)] += 1

        # Sort by frequency
        sorted_transitions = sorted(transitions.items(), key=lambda x: x[1], reverse=True)

        # Plot top transitions
        top_n = min(15, len(sorted_transitions))
        labels = [f"{old} → {new}" for (old, new), _ in sorted_transitions[:top_n]]
        values = [count for _, count in sorted_transitions[:top_n]]

        y_pos = np.arange(len(labels))
        colors = plt.cm.viridis(np.linspace(0.3, 0.9, len(labels)))

        ax.barh(y_pos, values, color=colors, alpha=0.8)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(labels, fontsize=9)
        ax.set_xlabel('Number of Transitions', fontsize=12)
        ax.set_title('Symptom State Transitions', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3, axis='x')

        # Add value labels
        for i, v in enumerate(values):
            ax.text(v + max(values) * 0.01, i, f' {v}', va='center', fontsize=9)

    def plot_transmission_network_stats(self, ax):
        """Plot transmission network statistics"""
        # Count offspring for each infected person
        infectors = self.infections['infector_id']
        valid_infectors = infectors[infectors != -1]
        offspring_counts = Counter(valid_infectors)

        # Distribution of offspring
        offspring_values = list(offspring_counts.values())
        max_offspring = max(offspring_values) if offspring_values else 0

        counts, bins = np.histogram(offspring_values, bins=range(0, max_offspring + 2))

        ax.bar(bins[:-1], counts, width=0.8, alpha=0.7, color='#3498db')
        ax.set_xlabel('Number of Secondary Infections per Person', fontsize=12)
        ax.set_ylabel('Number of People', fontsize=12)
        ax.set_title('Distribution of Secondary Infections (Offspring Distribution)',
                    fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)

        # Add statistics text
        if offspring_values:
            mean_offspring = np.mean(offspring_values)
            median_offspring = np.median(offspring_values)
            stats_text = f'Mean: {mean_offspring:.2f}\nMedian: {median_offspring:.1f}'
            ax.text(0.7, 0.95, stats_text, transform=ax.transAxes,
                   fontsize=10, verticalalignment='top',
                   bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))

    def plot_incubation_period(self, ax):
        """Plot distribution of time from infection to symptom onset"""
        # Find symptom onset times (first non-exposed symptom)
        incubation_periods = []

        for infection in self.infections:
            person_id = infection['person_id']
            infection_time = infection['time']

            # Find first symptom change for this person
            person_symptoms = self.symptom_changes[
                self.symptom_changes['person_id'] == person_id
            ]

            if len(person_symptoms) > 0:
                # Sort by time
                person_symptoms = person_symptoms[np.argsort(person_symptoms['time'])]
                first_symptom_time = person_symptoms[0]['time']
                incubation = first_symptom_time - infection_time

                if incubation >= 0:
                    incubation_periods.append(incubation)

        if incubation_periods:
            ax.hist(incubation_periods, bins=30, alpha=0.7, color='#2ecc71', edgecolor='black')
            ax.set_xlabel('Incubation Period (days)', fontsize=12)
            ax.set_ylabel('Number of Cases', fontsize=12)
            ax.set_title('Distribution of Incubation Periods', fontsize=14, fontweight='bold')
            ax.grid(True, alpha=0.3)

            # Add statistics
            mean_inc = np.mean(incubation_periods)
            median_inc = np.median(incubation_periods)
            ax.axvline(mean_inc, color='red', linestyle='--', linewidth=2, label=f'Mean: {mean_inc:.2f} days')
            ax.axvline(median_inc, color='blue', linestyle='--', linewidth=2, label=f'Median: {median_inc:.2f} days')
            ax.legend()
        else:
            ax.text(0.5, 0.5, 'No incubation data available', ha='center', va='center',
                   transform=ax.transAxes, fontsize=12)

    def plot_cumulative_infections(self, ax):
        """Plot cumulative infections over time"""
        times = np.sort(self.infections['time'])
        cumulative = np.arange(1, len(times) + 1)

        ax.plot(times, cumulative, linewidth=2, color='#e74c3c')
        ax.set_xlabel('Time (days)', fontsize=12)
        ax.set_ylabel('Cumulative Infections', fontsize=12)
        ax.set_title('Cumulative Infections Over Time', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)
        ax.fill_between(times, 0, cumulative, alpha=0.3, color='#e74c3c')

    def plot_symptom_timeline(self, ax):
        """Plot symptom changes over time"""
        # Count symptom changes by time
        times = self.symptom_changes['time']
        bins = np.arange(0, times.max() + 1, 1)
        counts, edges = np.histogram(times, bins=bins)

        ax.bar(edges[:-1], counts, width=0.8, alpha=0.7, color='#9b59b6')
        ax.set_xlabel('Time (days)', fontsize=12)
        ax.set_ylabel('Number of Symptom Changes', fontsize=12)
        ax.set_title('Symptom State Changes Over Time', fontsize=14, fontweight='bold')
        ax.grid(True, alpha=0.3)

    def create_all_visualizations(self, output_dir='outputs'):
        """Create all visualizations and save to files"""
        import os
        os.makedirs(output_dir, exist_ok=True)

        print("\n" + "="*60)
        print("GENERATING VISUALIZATIONS")
        print("="*60)

        # Create main figure with subplots
        fig = plt.figure(figsize=(20, 12))
        gs = fig.add_gridspec(3, 2, hspace=0.3, wspace=0.3)

        ax1 = fig.add_subplot(gs[0, 0])
        ax2 = fig.add_subplot(gs[0, 1])
        ax3 = fig.add_subplot(gs[1, 0])
        ax4 = fig.add_subplot(gs[1, 1])
        ax5 = fig.add_subplot(gs[2, 0])
        ax6 = fig.add_subplot(gs[2, 1])

        print("\n1. Epidemic curve...")
        self.plot_epidemic_curve(ax1)

        print("2. Symptom progression...")
        self.plot_symptom_progression(ax2)

        print("3. Transmission network stats...")
        self.plot_transmission_network_stats(ax3)

        print("4. Incubation period distribution...")
        self.plot_incubation_period(ax4)

        print("5. Cumulative infections...")
        self.plot_cumulative_infections(ax5)

        print("6. Symptom timeline...")
        self.plot_symptom_timeline(ax6)

        # Add title to the whole figure
        fig.suptitle('Epidemiology Simulation Analysis Dashboard',
                    fontsize=18, fontweight='bold', y=0.995)

        # Save the combined figure
        output_path = f'{output_dir}/simulation_dashboard.png'
        plt.savefig(output_path, dpi=150, bbox_inches='tight')
        print(f"\nSaved dashboard to: {output_path}")

        plt.close()

        # Create a detailed summary report
        self.create_summary_report(output_dir)

    def create_summary_report(self, output_dir):
        """Create a text summary report"""
        report_path = f'{output_dir}/simulation_summary.txt'

        with open(report_path, 'w') as f:
            f.write("="*70 + "\n")
            f.write("EPIDEMIOLOGY SIMULATION SUMMARY REPORT\n")
            f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("="*70 + "\n\n")

            # Recompute statistics and write to file
            import sys
            from io import StringIO

            # Capture stdout
            old_stdout = sys.stdout
            sys.stdout = StringIO()

            self.compute_statistics()

            output = sys.stdout.getvalue()
            sys.stdout = old_stdout

            f.write(output)

        print(f"Saved summary report to: {report_path}")


def main():
    """Main execution function"""
    h5_path = '../simulation_events.h5'

    print("\n" + "="*70)
    print("EPIDEMIOLOGY SIMULATION VISUALIZER")
    print("="*70)

    # Create analyzer
    analyzer = SimulationAnalyzer(h5_path)

    # Compute and display statistics
    stats = analyzer.compute_statistics()

    # Create all visualizations
    analyzer.create_all_visualizations()

    print("\n" + "="*70)
    print("ANALYSIS COMPLETE")
    print("="*70)
    print("\nOutputs saved to: june_analysis/outputs/")
    print("  - simulation_dashboard.png: Combined visualization dashboard")
    print("  - simulation_summary.txt: Detailed statistics report")


if __name__ == '__main__':
    main()
