geography:
  data_dir: "1911_data/geography"
  levels: [SGU, MGU]

venues:
  data_dir: "1911_data/venues"
  config_file: "yaml/1911/households_config.yaml"
  static_geo_unit: "SHERBURN_1"

population:
  type: "explicit_batch"
  data_dir: "1911_data/population"
  column_mapping:
    age: Age
    sex: Sex

timeline:
  enabled: true
  steps:
    - type: "distributor"
      config: "yaml/1911/distribution_config.yaml"

households:
  enabled: false

serialization:
  enabled: true
  output_dir: "output/1911"
  filename: "1911_world.h5"
  compression: "gzip"
