geography:
  data_dir: data/geography
  load_all: false
  filter:
    level: MGU
    codes: ''
    file: may/filters/example_mgu.txt
population:
  data_dir: data/population
  demographics_male_file: demographics_male.csv
  demographics_female_file: demographics_female.csv
venues:
  data_dir: data/venues
  config_file: yaml/venues/venues_config.yaml
  export_file: venue_allocations.csv
households:
  data_dir: data/households
  data_file: households.csv
  config_file: yaml/households/households_config.yaml
  strategy_file: yaml/households/allocation_strategy.yaml
  export_file: household_allocations.csv
