import logging

logger = logging.getLogger("geographical_unit")

class GeographicalUnit:
    """
    Represents a single geographical unit at any level (SGU, MGU, LGU).
    Generic class that works with any geography, past or present.
    """

    __slots__ = [
        'id',
        'name',
        'level',
        'coordinates',
        'parent',
        'children',
        'venues',
        'people',
        'properties',
    ]
    
    def __init__(self, id, name, level, coordinates=None, parent=None):
        self.id = id              # Unique numeric ID (generated by code)
        self.name = name          # Unique name/identifier (e.g., "E00004320", "London")
        self.level = level        # "SGU", "MGU", or "LGU"
        self.coordinates = coordinates  # Tuple of (latitude, longitude) or None
        self.parent = parent      # Reference to parent unit (one level up)
        self.children = []        # List of child units (one level down)
        self.venues = []          # List of venues in this geographical unit
        self.people = []          # List of people in this geographical unit (populated at smallest level)
        self.properties = {}      # Extensible dict for any additional data

    def add_child(self, child):
        """Add a child unit and set this as its parent"""
        self.children.append(child)
        child.parent = self

    def add_venue(self, venue):
        """Add a venue to this geographical unit"""
        self.venues.append(venue)

    def add_person(self, person):
        """Add a person to this geographical unit"""
        self.people.append(person)

    def get_venues_by_type(self, venue_type):
        """Get all venues of a specific type in this geographical unit"""
        return [v for v in self.venues if v.type == venue_type]

    def get_ancestors(self):
        """Get all ancestor units up the hierarchy"""
        ancestors = []
        current = self.parent
        while current is not None:
            ancestors.append(current)
            current = current.parent
        return ancestors

    def get_ancestor_by_level(self, level):
        """
        Get ancestor unit at a specific level.

        Args:
            level: Level name (e.g., "LGU", "MGU", "SGU")

        Returns:
            GeographicalUnit at that level or None if not found
        """
        # Check if we're already at the requested level
        if self.level == level:
            return self

        # Traverse up the hierarchy
        current = self.parent
        while current is not None:
            if current.level == level:
                return current
            current = current.parent

        return None

    def get_descendants(self, level=None):
        """
        Get all descendant units. If level specified, only return that level.
        """
        descendants = []
        for child in self.children:
            if level is None or child.level == level:
                descendants.append(child)
            descendants.extend(child.get_descendants(level))
        return descendants

    def __repr__(self):
        venue_info = f", {len(self.venues)} venues" if self.venues else ""
        people_info = f", {len(self.people)} people" if self.people else ""
        return f"<{self.level} #{self.id}: {self.name} ({len(self.children)} children{venue_info}{people_info})>"
