site_name: MAY Docs

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [../.]
          options:
            show_submodules: true
            allow_inspection: true
            relative_crossrefs: true
  - autorefs
  - search
  - awesome-nav

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

validation:
  links:
    not_found: ignore